# Generated by Django 3.1.7 on 2021-04-22 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormOfCoffin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_form', models.CharField(max_length=255, verbose_name='Название модели')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('color_coffin', models.CharField(max_length=255, verbose_name='Цвет дерева')),
                ('image', models.ImageField(upload_to='forms/')),
                ('form_description', models.CharField(max_length=255, verbose_name='Описание модели гроба')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='qwerty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
                ('service', models.TextField(max_length=20, verbose_name='Похороны/кремация')),
                ('date_of_funeral', models.DateField(verbose_name='Дата похорон')),
                ('price_of_funeral', models.CharField(max_length=20, verbose_name='Приблизительная сумма расходов')),
                ('about', models.TextField(blank=True, verbose_name='Коммантарий')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Coffin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffin_name', models.CharField(max_length=255, verbose_name='Название гроба')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='coffins/')),
                ('coffin_description', models.CharField(max_length=255, verbose_name='Описание гроба')),
                ('package_service', models.CharField(max_length=255, verbose_name='Пакет')),
                ('category_form_coffin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.formofcoffin', verbose_name='Модели гробов')),
            ],
            options={
                'verbose_name': 'Гроб',
                'verbose_name_plural': 'Гробы',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
