# Generated by Django 3.1.7 on 2021-04-09 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formofcoffin',
            name='category_form_coffin',
        ),
        migrations.AddField(
            model_name='coffin',
            name='category_form_coffin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.formofcoffin', verbose_name='Модели гробов'),
            preserve_default=False,
        ),
    ]
